spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.30.135:3306/yutest
    type: com.zaxxer.hikari.HikariDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.yu.test.config
  type-aliases-package: com.yu.test.domain
